### ISSUE TITLE
Ability to display channels in relation to other channels

### ISSUE THREAD

**Issue by mtrefethen-m** [event-catalog/eventcatalog#1172]
### Use Case

I am wondering if there is a way to relate channels to other channels for the purposes of better displaying a producer publishing to a "topic" channel that has multiple "subscriber" channels with different consumers. In my environments it is common for a producer to produce many different types of events into a stream based on domain and subsystem, which then are distributed to many differing subscriptions based on business rules. Right now I'm describing that in one channel but that's really not accurate since the topics and subscriptions all have different addresses and I'm having to explain the multiplicity in text when it's easier to understand graphically. The other option I have is to use a separate diagramming tool and embed the image in the MD but I feel that defeats the purpose a little.

Contrived Example:
```
General naming pattern:
  Topic:             platform.event.{domain}.{system}.{sub-system}
                                  |
  Subscriptions:     {topic}.sub.{external-consumer}.{attributes}


  order.inventory.reservation
                   |
               filtered
                   |
  order.inventory.reservation.sub.plant-operations.schedule-build-event
  order.inventory.reservation.sub.crm.wholesale-sales.inventory-release-event
  order.inventory.reservation.sub.data-warehousing.all-events
  order.inventory.reservation.sub.notifications.all-failure-events
  ...etc...
```

If this is possible already, any information would be appreciated, otherwise I look forward to hearing thoughts and considerations.

Also, thank you everyone for all the hard work, the tool is excellent.

### Proposed Solution

A mechanism to describe a topic or stream being filtered into a multiplicity of subscriptions or other streams delivered to disparate consumers

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).

**Comment by mtrefethen-m** [comment]
Would that display as a link in the visualizer and also could it be enhanced to allow an option label on the arrow like `subscribes` or `fiters`?

**Comment by carlosallexandre** [comment]
Hey @mtrefethen-m,  

I’d like to clarify something—when implementing this filtering logic between channels/streams, do you typically use a **pipe** (e.g., **EventBridge Pipes**), or do you rely on another mechanism?  

Would love to understand how you're currently handling this! 🚀

**Comment by boyney123** [comment]
Closing this — channel-to-channel routing is now supported via the `routes` property on channel frontmatter, and renders in the visualiser as a "routes to" edge.

Example for the scenario in this issue:

```yaml
# channels/order.inventory.reservation/index.md
id: order.inventory.reservation
name: Order Inventory Reservation
version: 1.0.0
routes:
  - id: order.inventory.reservation.sub.plant-operations.schedule-build-event
    version: 1.0.0
  - id: order.inventory.reservation.sub.crm.wholesale-sales.inventory-release-event
    version: 1.0.0
  - id: order.inventory.reservation.sub.data-warehousing.all-events
    version: 1.0.0
```

Each downstream channel is its own resource with its own address/protocol/subscribers, and the visualiser draws the topic → subscription fan-out with "routes to" labels on the edges.

If you'd like the edge label to be configurable (e.g. `subscribes`, `filters`) per @mtrefethen-m's earlier comment, please open a new focused issue for that.
