### ISSUE TITLE
Allow users to add "related resources" to all resources in EventCatalog

### ISSUE THREAD

**Issue by boyney123** [event-catalog/eventcatalog#1174]
### Use Case

I have some users that want to relate resources together, not in a group (domain point of view), but this event (resource) related to this other event, or service etc.

It's just a way that users can group things up visually and let there own catalog users know what resources are related to each other.

Kind of like when you read a doc page and it says "You may also like...".

This would introduce a new field called `**relatedResources**`

```yaml
---
id: Orders
name: Orders
version: 0.0.1
summary: |
  Domain that contains order related services and messages.
owners:
    - dboyne
events:
    - id: OrderPlaced
relatedResources:
   - id: OrderOwned
  - id: OrderCreated
  - id: PaymentService
  - id: PaymentChannel
badges:
    - content: Payment Domain
      backgroundColor: blue
      textColor: blue
---
```

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).
