### ISSUE TITLE
Add ability to add subdomains

### ISSUE THREAD

**Issue by boyney123** [event-catalog/eventcatalog#1175]
### Use Case

Just looking for feedback, but feature request I'm getting from users is the ability to add subdomians to domains.

### Proposed Solution

Either we have `subdomain` in the frontmatter of the `domain` or we just have nested `domains`.

I think I lean towards domain > subdomain.

```
---
id: Payment
name: Payment
version: 0.0.2
summary: |
  Domain that contains payment related services and messages.
owners:
    - dboyne
subdomains:
  - PaymentSubDomain (just another domain id)
badges:
    - content: Payment Domain
      backgroundColor: blue
      textColor: blue
---
```

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).
