### ISSUE TITLE
Adding support for Aggregates, and other DDD concepts

### ISSUE THREAD

**Issue by callingmybluff** [event-catalog/eventcatalog#1296]
## Lacking

When working with DDD, we lack the following in the current implementation

- Link DDD activities (like event storming) to the event catalog (i.e. missing fine-grained details)
- Link implementation with the catalog.
- Ambiguous ownership of domain logic.
- Tight coupling between different aggregates in one service.

## Objective

Integrate Domain-Driven Design (DDD) concepts (Aggregates, Entities, and Value Objects) into the event catalog to model complex business domains more effectively, make documentation more complete, and enforce domain invariants.

## Definitions

Add an aggregate concept, which can be defined by

### Aggregates belong to a domain

Aggregates belong to a single domain.

### Ubiquitous Language

Just like you do today for domain-level. Aggregate could have its own language as well. I would expect that domain language explorer can show or link aggregates.

### Content

An aggregate has its own input and output. It can receive events, commands, queries, and send / trigger them all as well. In addition, it can have entities and value objects.

Entities and value objects are basically objects (one with an id and the other without one) but you will not find them in OpenAPI specs (think of database models)

# Location

In concept, an aggregate reside inside a service, and one aggregate belong to exactly one service. However, one service could have one or more aggregates.

### Implementation Notes

I believe an aggregate is an extension of the current `Service`

From my experience using the catalog, I identified the following points that need to be worked out

## Flows

An aggregate is a detailed view, and it described how it works inside the system. Meaning that it is one level deeper in a service-level flow.

There should be a way to dive from a service-level flow to an aggregate flow (i.e. looking inside a service.) The hard part in that is that one service-level flow could have multiple aggregate-level flows. The following could be a possible solution

**Service-level flow (same as now)**

```yaml
id: CycleCount
name: Cycle Count
version: 1.0.0
summary: |
  WMS sends a cycle count to S4 to register it
steps:
  - id: wms
    title: NA
    externalSystem:
      name: WMS
    next_step:
    - id: request_cycle_count

  - id: request_cycle_count
    title: NA
    message:
      id: RequestCycleCount
    next_steps:
    - id: my_service

  - id: my_service
    title: NA
    service:
      id: ServiceThatHasCycleCountAggregate
    next_steps:
    - id: post_cyc
    - id: cyc_posted

  - id: post_cyc
    title: NA
    message:
      id: PostCycleCountToS4
    next_step:
      id: s4

  - id: cyc_posted
    title: NA
    message:
      id: CycleCountPosted

  - id: s4
    title: NA
    service:
      id: S4

``` 

**Aggregate-level flow 1** 

```yaml
id: CycleCountRequestReceiving
name: Cycle Count Request Receiving
version: 1.0.0
parentFlow:
  id: CycleCount
  service: my_service
summary: |
  WMS sends a cycle count to S4 to register it
steps:
  - id: request_cycle_count
    title: NA
    message:
      id: RequestCycleCount
    next_steps:
    - id: cycle_count_received

  - id: cyc_received
    title: NA
    message:
      id: CycleCountReceived
``` 

**Aggregate-level flow 2**

```yaml
id: CycleCountRequestPosting
name: Cycle Count Request Posting
version: 1.0.0
parentFlow:
  id: CycleCount
  service: my_service
summary: |
  WMS sends a cycle count to S4 to register it
steps:
  - id: request_cycle_count
    title: NA
    message:
      id: RequestCycleCount
    next_steps:
    - id: cycle_count_requested
... etc
``` 
Here, you can see that I did not display the aggregates or refer to them, as the name of the aggregates is not relevant in the flows usually. What is relevant is its commands, queries, and events imo.

To draw this, there are two levels of difficulties 😆 
* Easy => Each service that can be expanded has a plus sign, and once clicked on that, it displayed the list of children flow that the user can choose one to view
* Medium => The plus will display all children flows together (simply clubbing all the children flows in one flow)
* Hard => The parent flow would replace the service with its children flows and keep a container that can be collapsed back.

## Schema

Usually, you would not find the schema of an aggregate in any standard catalog (like open API). Both Entity and Value objects do not have a published schema usually.

Commands, queries, and events could have a published schema, but there could be an "internal" schema.

For instance, an aggregate we have publishes an event called `SalesOrderAdded` that is internal (and has a contract), and as a result of that, we trigger another domain event `ProductionOrderSalesInfoAdded` that is published with its *different* schema on Confluent.

I think this is easily solved by replying on manual creation of schema files.

## Location

Following current implementation, an aggregate belongs to one domain, and service as well. But the question is, should services restricted to one domain only?
There is infrastructure or application service that span over multiple domains, and if we are thinking of supporting that in the future, it would be more "future-prune" to have the aggregates referring to the services only

Today we find

> root
> |__ domains
> |____ Domain1
> |______ services
> |________ Service A
> |______ flows
> |________ Domain flow I
> 

With the above, it would look like

> root
> |__ domains
> |____ Domain1
> |______ services
> |________ Service A
> |______ flows
> |________ Domain flow I
> |______ **aggregates**
> |________ Aggregate A
> |______ **flows**
> |________ Domain flow I
> |__ **services** (cross-domain services)
> |____ same structure as domain-specific services
> |__ **flows** (cross-domain flows)
> |____ same structure as domain-specific flows

### Community Notes

* Useful intro to join the conversation => https://lostechies.com/jimmybogard/2008/05/21/entities-value-objects-aggregates-and-roots/

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).
