### ISSUE TITLE
Show message custom badge in NodeGraph

### ISSUE THREAD

**Issue by VitaliiBalash** [event-catalog/eventcatalog#1352]
### Use Case

EventCatalog allows users to override the default badge in the sidebar: https://www.eventcatalog.dev/docs/development/customization/customize-sidebars/documentation-sidebar#default-side-bar-options-list_view

It would be useful to have a similar functionality for NodeGraph nodes.

<img width="1161" alt="Image" src="https://github.com/user-attachments/assets/e6567f5c-df6c-4da1-a6ae-8d6be957b909" />

### Proposed Solution

We can either reuse the existing API, or create a new one.

If decided to use the existing API, the change is quite simple (in each related node):
1. get the badge [here](https://github.com/event-catalog/eventcatalog/blob/main/eventcatalog/src/components/MDX/NodeGraph/Nodes/Query.tsx#L23) 
2. use it if provided [here](https://github.com/event-catalog/eventcatalog/blob/main/eventcatalog/src/components/MDX/NodeGraph/Nodes/Query.tsx#L40): `{sidebar.badge ?? 'Query'}`

If a new API is introduced, it might make sense to treat it as a general resource configuration and deprecate sidebar.badge to prevent any confusion.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).

**Comment by boyney123** [comment]
Yeah I like this idea @VitaliiBalash 

What about this 

```
---
id: UpdateShipmentStatus
name: Update shipment status
version: 0.0.1
summary: |
  POST request that will update the status of a shipment, identified by its shipmentId.
owners:
    - dboyne
schemaPath: schema.json
sidebar:
  badge: 'POST'
styles:
  node:
    color: 'blue'
    icon: 'RandomIcon'
---
```

We introduce `styles` for each resource, and here a `node` section, which lets you override the color and icon shown in the nodes (visualizer)
