### ISSUE TITLE
Allow visualization of relations between entities

### ISSUE THREAD

**Issue by SlimeBolt** [event-catalog/eventcatalog#1489]
### Use Case

It would be great if entity relations could be visualized.

You can currently already link entities through documentation, but you can't click through or see these links with any clear purpose. [Current Docs](https://www.eventcatalog.dev/docs/development/guides/domains/entities/adding-entities)

It would be amazing if this could be visualized

### Proposed Solution

Allow a visualizer to translate the index.mdx to a diagram, in a similar way that events are translated. The end result would be an entity relationship diagram such as this

![ERD](https://d2slcw3kip6qmk.cloudfront.net/marketing/pages/chart/seo/ERD/discovery/erd-example.svg)

### Implementation Notes

You can translate the _array_ and _required_ attribute to the symbols on the lines, the rest is already info present in the index.mdx for when you create one or multiple entities.

![ERD Symbols](https://d2slcw3kip6qmk.cloudfront.net/marketing/pages/chart/erd-symbols/ERD-Notation.PNG)

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).

**Comment by Mastermindzh** [comment]
Would definitely improve the product!
If anything is unclear or extra help is needed please don't be afraid to ask 😄

**Comment by boyney123** [comment]
Thanks! Would this just be for entities documented?

Sounds great to me, something I have in mind

<img width="506" alt="Image" src="https://github.com/user-attachments/assets/b5461ec7-3833-4f06-bc9f-f209a60968f4" />

Currently working on a few other things, but might pick this up at some point. Also let me know if you have any budget, could make this happen sooner! 🙏🍻

**Comment by boyney123** [comment]
@SlimeBolt at the moment entities have `properties` which are just a list of things.

How would you expect to link the properties together? Between entities

**Comment by SlimeBolt** [comment]
@boyney123 through that `properties`  attribute.
You can already make links like so, as an example on the Creating entities page
`  - name: orderItems
    type: array
    items:
      type: OrderItem # Assuming an OrderItem entity exists`

So i'd say that this creates a link to an OrderItem, perhaps that on the order items you can give one (or more) of the properties a primary key, the same way you could a database, and that is what it points to

**Comment by boyney123** [comment]
Not native support, but plantuml was added to EventCatalog that can help with this https://www.eventcatalog.dev/docs/development/components/plantuml

**Comment by boyney123** [comment]
Hi 👋 — I’ve been working on entity modeling using frontmatter-based schema definitions (similar to EventCatalog’s style), and I’d love to propose a way to improve entity relationship modeling with support for explicit references.

 Proposal: Add support for references and referencesIdentifier in properties

This would allow us to define relationships between entities like so:
```
- name: paymentMethodId
  type: UUID
  required: true
  references: PaymentMethod
  referencesIdentifier: paymentMethodId
  relationType: uses
```

This helps:
- Declare a foreign key (paymentMethodId) to another entity (PaymentMethod)
- Specify which field in the target entity (paymentMethodId) it maps to
- Annotate the relationship with a relationType (e.g., uses, belongsTo, references)

✅ Benefits
- Enables automatic relationship resolution between entities
- Allows future UI features like clickable links, diagrams, or dependency graphs
- Improves readability and tooling opportunities without breaking current structure

Would love to hear your thoughts on this

**Comment by boyney123** [comment]
Have something like this so far

<img width="1041" alt="Image" src="https://github.com/user-attachments/assets/c4cc2098-26d6-48bf-a5a8-bce2da2dfac6" />

Example

```
---
id: BillingProfile
name: BillingProfile
version: 1.0.0
identifier: billingProfileId
summary: Stores billing-related contact information and preferences for a customer, often used for invoices and communication.

properties:
  - name: billingProfileId
    type: UUID
    required: true
    description: Unique identifier for the billing profile.
  - name: customerId
    type: UUID
    required: true
    description: Identifier of the customer this billing profile belongs to.
    references: Customer
    referencesIdentifier: customerId
```
