### ISSUE TITLE
Cross linking of event fields.

### ISSUE THREAD

**Issue by donaldpipowitch** [event-catalog/eventcatalog#220]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

It would be lovely if we could link/reference from one event field to the field of a different event. Speaking about this view here:

<img width="944" alt="image" src="https://user-images.githubusercontent.com/1152805/156344058-46d16e4e-4655-4d6d-940a-1d7ad024384f.png">

### Motivation

Imagine you have `TradeCreated` event with the two fields `buyerId` and `sellerId`. It would be lovely if both fields could link/reference to an `id` field in a `UserCreated` event. That way people can jump to `UserCreated` and from here on check related fields or other related events.

This feature request is _not_ exactly about supporting `$ref` in JSON Schemas. As far as I know `$ref` references a _complete_ (sub)-schema. If `TradeCreated: buyerId` and `TradeCreated: sellerId` would reference `UserCreated: id` directly they would inherit the `description` of  `UserCreated: id` and could not provide there own. (But I might be wrong here.) So I'd still like to be able to write something like this:

```
UserCreated:
  properties:
    id:
      description: "Use this to reference any user."

TradeCreated:
  properties:
    buyerId:
      description: "References a user which has money and trades it for some goods."
    sellerId:
      description: "References a user which offers goods."
```

I wonder what would be the best way to support? Currently I could imagine two weeks:
- extend JSON Schema somehow (misusing fields like `$comment` or adding custom fields)
- provide an additional EventCatalog-specific document (something like a `sitemap.xml`, but for events)

In case of an EventCatalog-specific document it would be nice if we could design it in a way that it can be extended in the future. E.g. another feature we'd love to see would be placing events in "business process flows. E.g. something like this:

```
TradeRequested ----- TradeAccepted ----- TradeDelivered
               \
                 --- TradeRejected
```
