### ISSUE TITLE
AsyncAPI generator - preserve consumers/externalLinks

### ISSUE THREAD

**Issue by thim81** [event-catalog/eventcatalog#285]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

Currently the AsyncAPI generator does an excellent job, on generating new versions of the `schema.json` and updating the `index.md` files.

There is a small annoyance, the `consumers` & `externalLinks` get overwritten with each generation, while the rest of the index.md file remains untouched.

Example - before:

```yaml
version: 1.0.0-BETA
producers:
    - 'Mobile Sdk'
consumers:
    - 'Messaging Platform'
externalLinks:
    - label: AsyncAPI Specification
      url: https://messaging.com/#message-mobile.sdk.events.clicked
---
### Producers / Consumers  diagram
<NodeGraph />
```

Example - after:

```yaml
version: 1.0.0-BETA
producers:
    - 'Mobile Sdk'
consumers: []
externalLinks: []
---
### Producers / Consumers  diagram
<NodeGraph />
```

Is there a way to prevent the overwrite of the consumers/externalLinks when running `npm run generate`?

### Motivation

It would lower the maintenance of keeping the Event Catalog & the AsyncAPI specification in sync.

Currently we have to restore the overwritten `consumers` & `externalLinks` definitions.
