### ISSUE TITLE
CSS not loading when deploying event catalog as github pages

### ISSUE THREAD

**Issue by uditnarayan** [event-catalog/eventcatalog#639]
So I created an event catalog and setup a github action pipeline to build and deploy the catalog to github pages:

```
name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Build 🔧 
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
```

The deploy action here commits the build into a new branch gh-pages so that I can use the root of the branch as root of my static website. The event catalog loads like this:

![image](https://github.com/user-attachments/assets/bfd292d7-6dfa-49bc-814f-364fb6777dcf)

Looks like the files hosted inside _astro folder are not loaded, while it loads everything else correctly.
