### ISSUE TITLE
Semver versioning breaks NodeGraphs

### ISSUE THREAD

**Issue by boyney123** [event-catalog/eventcatalog#714]
**Example**

I have a domain (see below) and I link services to it (without any versions or using semver versions).

When I use the NodeGraph nothing is shown.

```
---
id: claims-processing-domain
name: Claims Processing
version: 0.0.1
services:
  - id: claims-submission-service
badges:
  - content: Core Domain
    backgroundColor: blue
    textColor: white
---
```

<img width="818" alt="image" src="https://github.com/user-attachments/assets/3745feb7-f94d-4259-8c55-0abf4f38bbcd">

Node graph calculations need to use SemVer to find the right versions I think.
