### ISSUE TITLE
Enable user inform services/sends/receives as list of string

### ISSUE THREAD

**Issue by carlosallexandre** [event-catalog/eventcatalog#719]
As user I want inform a list of services only with the id, without key/value. Such as:
```yml
id: Payment
name: Payment
version: 0.0.2
summary: |
  Domain that contains payment related services and messages.
owners:
    - dboyne
services:
    - SubscriptionService
    - PaymentService
``` 

As user I want be able inform a send/receive only with the id or with key/value.. 
```yml
id: SubscriptionService
version: 0.0.1
name: Subscription Service
summary: |
  Service that handles subscriptions
owners:
    - dboyne
receives:
  - id: SubscribeUser
    version: 0.0.1
  - PaymentReceived
sends:
  - id: UserSubscriptionStarted  
    version: *
  - SubscriptionCanceled
```
