### ISSUE TITLE
Add ability to link services through APIs or by other means

### ISSUE THREAD

**Issue by nahidakbar** [event-catalog/eventcatalog#832]
### Use Case

Fully acknowledge that this tool is for documenting event driven architecture. But not all integration between domains and services in a typical organisation is going to be event based.

Most will be a mixture of event based and more common forms of integrations such as:
* RESTful
* GraphQL
* GRPC
* SOAP
* other API based

When you visualise a service in the visualiser, it would be good to have a way to document other associations with services.

### Proposed Solution

Could be something as simple as this in service header

```
associations:
  - id: OtherService
    association:  consumes
    protocol: REST
```

not fast on specific format (e.g. above suggestion). More interested in the concept.

### Implementation Notes

Would want to see it in node graph

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).

**Comment by markallanson** [comment]
I think this is now partially supported using channels, but the current channel implementation does not go far enough to model what you are suggesting.

Currently channels are assigned to Messages. In reality though, a channel is used to transport a message from Service A to Service B.

For example, `Service A` might send message `CreateOrder` to `Service B` via `Channel A`, but `Service A` might also send it to `Service B` via `Channel B`.

A concrete example - a Command might easily be sent synchronously via gRPC but also asynchronously via Kafka depending on the context.

It would be nice to model this in the `sends` and `receives` of a service.

```
sends:
  - id: "CreateOrder"
    version: "1"
    channels:
       - id: "RpcChannel"
         version: "1"
         parameters:
            some_parameter: "hello" 
```

This communicates reality very clearly - that the service is sending CreateOrder via the RPC channel.

As far as I can tell, the current Channel infrastructure doesn't allow this to be modelled - @boyney123?

**Comment by markallanson** [comment]
I don't think the appearance in the visualizer itself would actually change from what's there right now?

**Comment by boyney123** [comment]
Ah yeah gotcha.

I do quite like this to be honest 

```
sends:
  - id: "CreateOrder"
    version: "1"
    channels:
       - id: "RpcChannel"
         version: "1"
         parameters:
            some_parameter: "hello" 
```

Who do you think owns the channel in this regard? Where should it be documented?

1. "This service sends this message, over this channel" I think is what you have.
2. "This service sends this message", "this message has this channel option", is what we have now.

I think your method is better, when I think about. Allowing services to specify which channels they consume and send messages to and from.... but needs thinking.

Maybe we support both patterns?
