### ISSUE TITLE
A more streamlined way of defining flows

### ISSUE THREAD

**Issue by markallanson** [event-catalog/eventcatalog#958]
### Use Case

I have been working through my first flows and find that having to place messages in their own step can lead the flow being hard to maintain and follow as you are working on it.

The following example is the flow I would like to "simplify" for the sake of this ticket

```
- id: Step 1
  service:
    id: ServiceA
  next_steps:
    - id: "EventX"

- id: "EventX"
  message:
   id: "EventX"
  next_steps: 
    - id: Service 2

- id: "Step 2"
  service: 
    id: ServiceB
```

### Proposed Solution

It would be nice to model the relationship between services in the `next_steps` construct, which could remove a lot of yaml required to build a flow.

For example, something like

```
- id: Step 1
  service:
    id: ServiceA
  next_steps:
    - id: "Step 2"
      label: Step Success
      usingMessage: 
        id: "EventX"
        version: "1"

- id: Step 2
  service:
    id: ServiceB
```

### Implementation Notes

It would be nice for the renderer to somehow collapse the message node when there's just one link between the producer and consumer, so larger flows don't "get so wide".

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).
