### ISSUE TITLE
YAML formatted JsonSchema are not rendered using the SchemaViewer

### ISSUE THREAD

**Issue by cdavernas** [event-catalog/eventcatalog#991]
### I tried this:

Add a `Schema` and `SchemaViewer` tags, pointing to a YAML file, to my event `index.md`.

### This happened:

The schema is displayed as raw text, and the schema viewer is not rendered.

![{1C2301D7-7B23-44C3-AA0E-F84A47E5F270}](https://github.com/user-attachments/assets/fe6ceace-bc7e-4c63-acc2-9e7fbff2093a)

### I expected this:

The schema to be formatted as YAML, and the viewer to be rendered.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by boyney123** [comment]
@cdavernas thanks! Can you share and example of our schema so we can easily replicate the issue?

**Comment by cdavernas** [comment]
@boyney123 Sure, here is a sample:

```yaml
type: object
properties:
  aggregateId:
    type: string
  createdAt:
    type: string
    format: date-time
  definitionId:
    type: string
    description: Gets the id of the newly created notification's definition
  key:
    type: string
    description: Gets the key of the newly created notification
  initiator:
    type: object
    properties:
      email:
        type: string
        description: Gets the email of the referenced user
    description: Gets the notification's initiator
  recipients:
    type: array
    items:
      type: object
      properties:
        email:
          type: string
          description: Gets the email of the referenced user
    description: Gets a list containing the newly created notification's recipients
  inputData:
    description: Gets the newly created notification's input data
```
